// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkujflamohrusfebhtga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrdWpmbGFtb2hydXNmZWJodGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODAzNTQsImV4cCI6MjA2Njk1NjM1NH0.aRgyAJGAPwx9jelqVn27hJPBDhITY6TxmNkpkhFUo_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});